### ISSUE TITLE
Lock required packages on min stability

### ISSUE THREAD

**Issue by jhuliano** [hellofresh/reagieren#14]
It would be nice if we locked the required versions to minor versions, or we might break stuff.
See https://github.com/hellofresh/reagieren/blob/master/composer.json#L22
Keep in mind we are already using this package for live stuff, even if things are going to change later we need some versioning stability.

**Comment by kieranajp** [comment]
I agree - tagging @italolelis as he needs to [release v5](https://github.com/italolelis/collections/blob/master/composer.json#L44) of Collections first :smile:

**Comment by italolelis** [comment]
Hey sorry for the very late response.... We've tagged a pre release here which should be enough for now, I'll tag collections as soon as I have all tests for it.
