### ISSUE TITLE
Message::getTimestamp() return type ambiguous

### ISSUE THREAD

**Issue by pedrotypes** [hellofresh/reagieren#7]
https://github.com/hellofresh/reagieren/blob/master/src/Message.php#L34

I think we should have more guarantees of what this returns. Either an instance of `DateTime` or, to keep it a string, at least format it in ISO_8601.

**Comment by italolelis** [comment]
True...
@kieranajp Can you take a look into this please?
Let's make sure we return a `\DateTimeImutable` which makes sense in this case
